[project]
name = "ai-engineering-bootcamp-prerequisites-workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=2.14.0",
    "groq>=1.6.0",
    "ipykernel>=7.3.0",
    "openai>=2.48.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "streamlit>=1.60.0",
]

[tool.uv.workspace]
members = [
    "apps/api",
    "apps/chatbot_ui",
]

[dependency-groups]
dev = [
    "matplotlib>=3.11.1",
]
